name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Java Application
        run: |
              cd Simple-Employee-Management  # Ensure we're in the correct directory
              mvn clean package -DskipTests  # Build the JAR file

      - name: Build Docker Image
        run: |
             cd Simple-Employee-Management
             docker build -t aryaa19/simple-employee-management:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aryaanil8319@gmail.com
          password: Arya.Anil@8319
      - name: Build Docker Image
        run: docker build -t aryaa19/simple-employee-management:latest Simple-Employee-Management/

      - name: Push Docker Image to Docker Hub
        run: docker push aryaa19/simple-employee-management:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Application
        run: |
          docker pull aryaa19/simple-employee-management:latest
          docker stop employee-management || true
          docker rm employee-management || true
          docker run -d -p 8080:8080 --name employee-management aryaa19/simple-employee-management:latest
